### ISSUE TITLE
add support for arm64

### ISSUE THREAD

**Issue by Cregin** [imoldman/DSYMCreator#1]
invalid binary file: /Users/mac/Downloads/DSYMCreator-master/App

不是说已经添加arm64支持了吗  请问为什么用arm64的binary出现这个。。

**Comment by imoldman** [comment]
目前 arm64 的支持只做了 class-dump的支持，也就是 --only-objc 模式，ida模式暂时不支持。如果你确实使用的是 only-objc，仍然有这个问题的话，请检查下是否带了 --arm64 的参数，这部分还在调整，所以没有文档化。如果仍然有问题，请把二进制文件email给我，多谢。

**Comment by Cregin** [comment]
了解了，谢谢
